TILE_SIZE = 16
FPS = 60
AMT_BOMBS = 30
AMT_ROWS = 16
AMT_COLS = 16
WINDOW_SIZE = (AMT_ROWS * TILE_SIZE * 2, AMT_COLS * TILE_SIZE * 2 + 50)
SCALED_WINDOW_SIZE = (WINDOW_SIZE[0] // 2, WINDOW_SIZE[1] // 2)
